### ISSUE TITLE
error during npm install in kali linux

### ISSUE THREAD

**Issue by shivamkumarchandel** [albinotonnina/albinotonnina.com#10]
root@SK:~/Desktop/MyWebsite/albinotonnina.com-master# npm install

> phantomjs-prebuilt@2.1.15 install /root/Desktop/MyWebsite/albinotonnina.com-master/node_modules/phantomjs-prebuilt
> node install.js

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! path sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn sh
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! spawn sh ENOENT
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-06T17_35_58_309Z-debug.log
root@SK:~/Desktop/MyWebsite/albinotonnina.com-master#

**Comment by albinotonnina** [comment]
Hi, sorry for the delay, something wrong with my notifications.
About this error, I'll try a wild guess first: npm version?
