### ISSUE TITLE
I want to derive from your work. Is it permitted by the license ?

### ISSUE THREAD

**Issue by memahesh** [albinotonnina/albinotonnina.com#15]
Hey, 
I want to make a derivate of your code to make my personal non-commercial portfolio. 
Is it permitted by the license?
Thanks in advance,

**Comment by asos-albinotonnina** [comment]
Hi, feel free to use the code. Just don't make a clone of it.
Word of advice, that's pretty old code, some users mentioned also that they had issues running it (in 2019).
