### ISSUE TITLE
Unable to launch using the readme commands

### ISSUE THREAD

**Issue by sudiksha711** [albinotonnina/albinotonnina.com#17]
Hi, 
Am I missing something as there seems to be a huge void between the read me and actual installation as I'm not able to successfully even get to running the downloaded project? Any help is appreciated. 

Thanks

npm run dev throws : 

Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'mode'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, parallelism?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.
     Loaders should be updated to allow passing options via loader options in module.rules.
     Until loaders are updated one can use the LoaderOptionsPlugin to pass these options to the loader:
     plugins: [
       new webpack.LoaderOptionsPlugin({
         // test: /\.xxx$/, // may apply this only for some modules
         options: {
           mode: ...
         }
       })
     ]
npm ERR! code ELIFECYCLE
npm ERR! errno 1

**Comment by tushar22211** [comment]
Try this - https://stackoverflow.com/questions/54694326/webpack-config-not-accepting-to-config-mode-option
Worked for me! :)

**Comment by sudiksha711** [comment]
> Try this - https://stackoverflow.com/questions/54694326/webpack-config-not-accepting-to-config-mode-option
> Worked for me! :)

Hey Tushar, downgrading sure helped but it's not the best, I will still take it for this project, Thankyou. It launches with report.html by default, however changing that to index.html, I still can't get the animations going in the project. Could you help me?




build has been removed.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:4000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1367:14)
    at listenInCluster (net.js:1408:12)
    at doListen (net.js:1517:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! albinotonnina@1.3.0 dev: `webpack-dev-server`
npm ERR! Exit status 1

**Comment by albinotonnina** [comment]
code completely refactores, should work now :)
