### ISSUE TITLE
grunt serve:dist error #2

### ISSUE THREAD

**Issue by nicholastjohnson** [albinotonnina/albinotonnina.com#2]
After implementing the workaround from Issue #1, I am getting a new issue that I'm unfamiliar with. Google and SO have been less than helpful.

Here's the error:

```
Looking for Modernizr references
Warning: Can't find your Modernizr development build at app/bower_components/modernizr/modernizr.js
          grunt-modernizr needs this path to avoid false positives

          Update your gruntfile via the modernizr.devFile config option
          See https://github.com/doctyper/grunt-modernizr#devfile-string for more details

          Use --force to continue.
```

**Comment by alexander-friedrich** [comment]
Same Issue here, for me it seems that app/bower_components/modernizr/modernizr.js is missing or the folder with the modernizr.js gets not created for some reason.

**Comment by albinotonnina** [comment]
code updated, two years later ;)
