### ISSUE TITLE
Weird subtitle, maybe forgotten accidentally?

### ISSUE THREAD

**Issue by gokhanipek** [albinotonnina/albinotonnina.com#52]
Or maybe just to give the impression of something is going wrong. Because afterwards we see the error screen.

 {
    "start": "6001",
    "end": "6003",
    "text": "dskf sdkjf98sy d9f8u"
  }

**Comment by albinotonnina** [comment]
Hello! Thank you! I'm afraid your second intuition is the correct one.
It's exactly supposed to give such impression :)
